# Generated by Django 6.0.7 on 2026-07-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='النبذة التعريفية')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الرابط')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('icon_class', models.CharField(blank=True, help_text='مثال: fa-brands fa-telegram أو fa-brands fa-tiktok', max_length=50, null=True, verbose_name='فئة الأيقونة (FontAwesome)')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('is_highlighted', models.BooleanField(default=False, help_text='إذا كان مفعلاً سيظهر الرابط بتصميم مختلف (لفت الانتباه)', verbose_name='مميز')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.profile', verbose_name='الملف الشخصي')),
            ],
            options={
                'verbose_name': 'الرابط',
                'verbose_name_plural': 'الروابط',
                'ordering': ['order'],
            },
        ),
    ]
