# Generated by Django 6.0.7 on 2026-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon_platform',
            field=models.CharField(choices=[('fa-brands fa-facebook', 'فيسبوك (Facebook)'), ('fa-brands fa-twitter', 'تويتر/X (Twitter)'), ('fa-brands fa-instagram', 'انستجرام (Instagram)'), ('fa-brands fa-tiktok', 'تيك توك (TikTok)'), ('fa-brands fa-snapchat', 'سناب شات (Snapchat)'), ('fa-brands fa-youtube', 'يوتيوب (YouTube)'), ('fa-brands fa-telegram', 'تيليجرام (Telegram)'), ('fa-brands fa-whatsapp', 'واتساب (WhatsApp)'), ('fa-brands fa-github', 'جيت هب (GitHub)'), ('fa-brands fa-linkedin', 'لينكد إن (LinkedIn)'), ('fa-solid fa-envelope', 'بريد إلكتروني (Email)'), ('fa-solid fa-globe', 'موقع إلكتروني (Website)'), ('other', 'غير ذلك (إدخال يدوي)')], default='other', max_length=50, verbose_name='أيقونة المنصة'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon_class',
            field=models.CharField(blank=True, help_text="في حال اختيار 'غير ذلك'، أدخل فئة الأيقونة هنا (مثال: fa-brands fa-discord)", max_length=50, null=True, verbose_name='أيقونة مخصصة'),
        ),
    ]
