# Generated by Django 6.0.7 on 2026-07-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_icon_platform_alter_link_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='bg_color',
            field=models.CharField(blank=True, help_text='مثال: #ff3366 أو اسم اللون، اتركه فارغاً للافتراضي', max_length=20, null=True, verbose_name='لون خلفية الرابط'),
        ),
        migrations.AddField(
            model_name='link',
            name='text_color',
            field=models.CharField(blank=True, help_text='مثال: #ffffff، اتركه فارغاً للافتراضي', max_length=20, null=True, verbose_name='لون النص والأيقونة'),
        ),
    ]
